/**
 * Breakpoint SoT (px) — edit here only.
 *
 * - SCSS: `breakpoints.scss` is generated by `build/sync-breakpoints-scss.ts` (Vite).
 * - Runtime: `theme.scss` `--breakpoint-*` ← `#{$mobile|$tablet|…}`; JS via `readBreakpointsPx()`.
 * - Mantine: `breakpointsEm` in `mantineTheme.ts`.
 *
 * Do not hardcode 1024/1040 in slideout / sidebar comments or media queries.
 */
export const BREAKPOINTS_PX = {
  mobile: 767,
  tablet: 1040,
  laptop: 1440,
  pc: 1441,
} as const;

export type BreakpointName = keyof typeof BREAKPOINTS_PX;

/** Convert px to em string (Mantine recommends em breakpoints). */
export const pxToEm = (px: number, base = 16): string => `${px / base}em`;

/** em breakpoints derived from BREAKPOINTS_PX — used by the Mantine theme. */
export const breakpointsEm = Object.fromEntries(
  Object.entries(BREAKPOINTS_PX).map(([name, px]) => [name, pxToEm(px)]),
) as Record<BreakpointName, string>;
